<?php

/**
 * This file declares the fields that will be shown on
 * the Themes custom post type
 * 
 * @author Syed Mohammed Hassan <contactsyedmh@gmail.com>
 * @since 1.0
 */
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_607f06e314efe',
	'title' => 'Theme Page Opener',
	'fields' => array(
		array(
			'key' => 'field_607f07e990290',
			'label' => 'Background Image',
			'name' => 'background_image',
			'type' => 'image',
			'instructions' => 'Background for the page opener section for this theme',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_607f089f90291',
			'label' => 'Theme Description',
			'name' => 'theme_description',
			'type' => 'textarea',
			'instructions' => 'A short excerpt (100 - 150 words) related to this theme',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => 1000,
			'rows' => '',
			'new_lines' => 'wpautop',
		),
		array(
			'key' => 'field_607f10683baeb',
			'label' => 'Theme Date',
			'name' => 'theme_year',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'd/m/Y',
			'return_format' => 'd/m/Y',
			'first_day' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'theme',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_607f093391a8e',
	'title' => 'In This Theme',
	'fields' => array(
		array(
			'key' => 'field_607f0c9895980',
			'label' => 'Printable',
			'name' => 'printable',
			'type' => 'repeater',
			'instructions' => 'Field groups for printables in this theme',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 3,
			'max' => 6,
			'layout' => 'table',
			'button_label' => 'Add Printable',
			'sub_fields' => array(
				array(
					'key' => 'field_607f0cae95981',
					'label' => 'Printable Title',
					'name' => 'title',
					'type' => 'text',
					'instructions' => 'Title for this printable in this theme',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_607f0cde95982',
					'label' => 'Printable Image',
					'name' => 'printable_image',
					'type' => 'image',
					'instructions' => 'Small image to represent this printable in the theme',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_607f0cf495983',
					'label' => 'Printable Description',
					'name' => 'printable_description',
					'type' => 'text',
					'instructions' => 'Very brief (up to 15 words) excerpt regarding this printable in the theme',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'theme',
			),
		),
	),
	'menu_order' => 2,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_607f0b3125d89',
	'title' => 'Theme Mockups',
	'fields' => array(
		array(
			'key' => 'field_607f0b44348a9',
			'label' => 'Theme Mockups Slider Images',
			'name' => 'theme_mockups_slider_images',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_607f0c630e64e',
			'min' => 2,
			'max' => 10,
			'layout' => 'table',
			'button_label' => 'Add Slider Mockup',
			'sub_fields' => array(
				array(
					'key' => 'field_607f0c630e64e',
					'label' => 'Theme Mockup Slider Image',
					'name' => 'theme_mockup_slider_image',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'theme',
			),
		),
	),
	'menu_order' => 3,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_607f0d830fdf4',
	'title' => 'Theme Guide',
	'fields' => array(
		array(
			'key' => 'field_607f0d92eeb33',
			'label' => 'About theme guide',
			'name' => 'about_theme_guide',
			'type' => 'textarea',
			'instructions' => 'Brief excerpt (100 - 150 words) regarding the theme guide included within this theme',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => 1000,
			'rows' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_607f0deaeeb34',
			'label' => 'Theme Guide Slider Images',
			'name' => 'theme_guide_slider_images',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_607f0dfceeb35',
			'min' => 2,
			'max' => 10,
			'layout' => 'table',
			'button_label' => 'Add Theme Guide Mockup',
			'sub_fields' => array(
				array(
					'key' => 'field_607f0dfceeb35',
					'label' => 'Theme Guide Mockup',
					'name' => 'theme_guide_mockup',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'medium',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'theme',
			),
		),
	),
	'menu_order' => 4,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_607f0eafc885b',
	'title' => 'Who Is',
	'fields' => array(
		array(
			'key' => 'field_607f0ec0afad3',
			'label' => 'Personality Name',
			'name' => 'personality_name',
			'type' => 'text',
			'instructions' => 'Name of the personality/character featured in this theme',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_607f0ee2afad4',
			'label' => 'Personality Description',
			'name' => 'personality_description',
			'type' => 'text',
			'instructions' => 'Brief excerpt (100 - 150 words) regarding the personality/character featured in this theme',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => 1000,
		),
		array(
			'key' => 'field_607f0f0aafad5',
			'label' => 'Personality Portrait',
			'name' => 'personality_portrait',
			'type' => 'image',
			'instructions' => 'Portrait of the personality/character featured in this theme',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'theme',
			),
		),
	),
	'menu_order' => 5,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_607f0f6f090b6',
	'title' => 'Book Recommendations',
	'fields' => array(
		array(
			'key' => 'field_607f0f7a14ab2',
			'label' => 'Recommendations',
			'name' => 'recommendations',
			'type' => 'post_object',
			'instructions' => 'Books to recommend with this theme',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'product',
			),
			'taxonomy' => '',
			'allow_null' => 0,
			'multiple' => 1,
			'return_format' => 'object',
			'ui' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'theme',
			),
		),
	),
	'menu_order' => 6,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'key' => 'group_607f0f3145872',
	'title' => 'Get This Theme',
	'fields' => array(
		array(
			'key' => 'field_607f0f3a11eb0',
			'label' => 'Final Call To Action',
			'name' => 'final_call_to_action',
			'type' => 'textarea',
			'instructions' => 'Up to 150 words to conclude the page',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => 1000,
			'rows' => '',
			'new_lines' => 'wpautop',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'theme',
			),
		),
	),
	'menu_order' => 7,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;